
- name: 安装 haproxy
  yum: name=haproxy state=latest

- name: 创建 haproxy 配置目录
  file: name=/etc/haproxy state=directory

- name: 配置 haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: 安装 keepalived
  yum: name=keepalived state=latest

- name: 创建 keepalived 配置目录
  file: name=/etc/keepalived state=directory

- name: 配置 keepalived 主节点
  template: src=keepalived-master.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "master"

- name: 配置 keepalived 备节点
  template: src=keepalived-backup.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "backup"

- name: 重启 haproxy 服务
  shell: systemctl enable haproxy && systemctl restart haproxy

- name: 重启 keepalived 服务
  shell: systemctl enable keepalived && systemctl restart keepalived
